// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var BoardField$ReactHooksTemplate = require("./BoardField.bs.js");

var rowStyle_000 = Css.borderBottom(Css.px(2), Css.solid, Css.hex("898989"));

var rowStyle_001 = /* :: */[
  Css.display(Css.flexBox),
  /* [] */0
];

var rowStyle = /* :: */[
  rowStyle_000,
  rowStyle_001
];

function BoardRow(Props) {
  var rowIndex = Props.rowIndex;
  var onSelectGamePiece = Props.onSelectGamePiece;
  var onSlideGamePiece = Props.onSlideGamePiece;
  var row = Props.row;
  return React.createElement("div", {
              className: Css.style(rowStyle)
            }, $$Array.of_list(List.mapi((function (colIndex, gamePiece) {
                        return React.createElement(BoardField$ReactHooksTemplate.make, {
                                    onSelectGamePiece: onSelectGamePiece,
                                    onSlideGamePiece: onSlideGamePiece,
                                    gamePiece: gamePiece,
                                    key: String(rowIndex) + String(colIndex)
                                  });
                      }), row)));
}

var make = BoardRow;

exports.rowStyle = rowStyle;
exports.make = make;
/* rowStyle Not a pure module */
