// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("React");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function MakePair(Config) {
  var _pair = React.createContext(Config[/* defaultValue */0]);
  var make = function (value, children) {
    return ReasonReact.wrapJsForReason(_pair.Provider, {
                value: value
              }, children);
  };
  var Provider = /* module */[/* make */make];
  var make$1 = function (children) {
    return ReasonReact.wrapJsForReason(_pair.Consumer, { }, children);
  };
  var Consumer = /* module */[/* make */make$1];
  return /* module */[
          /* _pair */_pair,
          /* Provider */Provider,
          /* Consumer */Consumer
        ];
}

exports.MakePair = MakePair;
/* React Not a pure module */
