// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function range(start, end_) {
  if (start >= end_) {
    return /* [] */0;
  } else {
    return /* :: */[
            start,
            range(start + 1 | 0, end_)
          ];
  }
}

function getGamePiece(x, y, player) {
  return /* record */[
          /* id */String(x) + String(y),
          /* x */x,
          /* y */y,
          /* player */player,
          /* gamePieceState : Default */0,
          /* kingStatus : Normal */1
        ];
}

function buildBoard(param) {
  var boardSize = range(0, 8);
  var boardRow = function (y, player) {
    return List.map((function (x) {
                  var match = x % 2;
                  var match$1 = y % 2;
                  if (match !== 0) {
                    if (match !== 1 || match$1 !== 0) {
                      return getGamePiece(x, y, /* Empty */2);
                    } else {
                      return getGamePiece(x, y, player);
                    }
                  } else if (match$1 !== 1) {
                    return getGamePiece(x, y, /* Empty */2);
                  } else {
                    return getGamePiece(x, y, player);
                  }
                }), boardSize);
  };
  return List.mapi((function (id, boardRow) {
                return /* record */[
                        /* id */id,
                        /* gamePieces */boardRow
                      ];
              }), List.map((function (y) {
                    var exit = 0;
                    if (y >= 3) {
                      if (y > 7 || y < 5) {
                        exit = 1;
                      } else {
                        return boardRow(y, /* White */0);
                      }
                    } else if (y >= 0) {
                      return boardRow(y, /* Red */1);
                    } else {
                      exit = 1;
                    }
                    if (exit === 1) {
                      return List.map((function (x) {
                                    return getGamePiece(x, y, /* Empty */2);
                                  }), boardSize);
                    }
                    
                  }), boardSize));
}

var Logic = /* module */[
  /* range */range,
  /* getGamePiece */getGamePiece,
  /* buildBoard */buildBoard
];

exports.Logic = Logic;
/* No side effect */
