// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Test(Props) {
  Props.name;
  return React.createElement("button", undefined, "Hello!");
}

var make = Test;

exports.make = make;
/* react Not a pure module */
